# -*- coding: utf-8 -*-
"""Barrier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IF0XbnUHUSimCOkE2s8E_MODOAmwuFj1
"""

from importlib.resources import contents
from scipy.interpolate import LinearNDInterpolator
import numpy as np


with open("/barrier_energies.txt", "r") as file:
    lines = []
    lines = [line.split() for line in file]
#    print(lines)

matrix = np.array(lines)
#print(matrix[0][0])

interpolant_map = np.zeros((21, 65))
step = 2
J_val = 0
for j in range (0, 64 , step) :
#      print("J_val : ", J_val)
      K_val = 0
      if j > 31 :
          step = 4
      for k in range (0, 21 , 2) :
#          print("K_val : ", K_val)
#          print(matrix[K_val][J_val])
          interpolant_map[k][j] = matrix[K_val][J_val]
          K_val = K_val + 1
      J_val = J_val + 1
      if J_val > 24:
        break

#print(interpolant_map)

rows, cols = np.indices(interpolant_map.shape)
mask = rows <= cols

interpolant_map_masked = np.where(mask, interpolant_map, np.nan)

x_coords = np.arange(0,32,2).tolist() + np.arange(32,65,4).tolist()
y_coords = np.arange(0, 21, 2)

points = []
values = []
for y in y_coords:
    for x in x_coords:
        if not np.isnan(interpolant_map_masked[y, x]):  # Check if value is not NaN (masked)
            points.append([x, y])
            values.append(interpolant_map_masked[y, x])

points = np.array(points)
values = np.array(values)

f = LinearNDInterpolator(points, values)

xnew = np.arange(0, 65, 1)
ynew = np.arange(0, 21, 1)
X, Y = np.meshgrid(xnew, ynew)
interpolated_map = f(X, Y)

#print(interpolated_map)

for j in range (0, 64) :
  for k in range (0, 21) :
    if np.isnan(interpolated_map[k][j]) :
      interpolated_map[k][j] = 0

#print(interpolated_map)

np.savetxt("/barrier_energies.csv", interpolated_map, delimiter=",")

