# -*- coding: utf-8 -*-
"""Histogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CB8eAsF8n94nmCbVSDbCWnvcZ2GQsVA
"""

import numpy as np
import matplotlib.pyplot as plt


#Read data
with open("/spectrum_info.txt", "r") as file:
  # Read all lines
  lines = file.readlines()

# Create arrays
gamma = []
partition_func_cov = []
partition_func_vdw = []
partition_func_inf = []

#Iterate on each line
for line in lines:
  elements = line.strip().split()
  gamma.append(float(elements[0]))
  partition_func_cov.append(float(elements[1]))
#  partition_func_vdw.append(float(elements[2]))
#  partition_func_inf.append(float(elements[3]))

#Convert to numpy arrays
gamma = np.array(gamma)
partition_func_cov = np.array(partition_func_cov)
#partition_func_vdw = np.array(partition_func_vdw)
#partition_func_inf = np.array(partition_func_inf)

# Define the number of bins
num_bins = 100  # Adjust as needed

# Create logarithmic bins
bins = np.logspace(np.log10(gamma.min()), np.log10(gamma.max()), num_bins + 1)

# Create histograms with logarithmic bins
plt.hist(gamma, bins=bins, weights=partition_func_cov, label='Covalent', alpha=0.7, histtype='bar')
#plt.hist(gamma, bins=bins, weights=partition_func_vdw, label='Vdw', alpha=0.7, histtype='bar')
#plt.hist(gamma, bins=bins, weights=partition_func_inf, label='Free Particles', alpha=0.7, histtype='bar')

# Set x-axis to logarithmic scale and specify limits
plt.xscale('log')
plt.xlim(0.0000001, 1000)  # Set x-axis limits

# # Add labels and title
plt.xlabel('Gamma')
plt.ylabel('Partition Function')
plt.title('Histogram of Partition Function vs Gamma')
plt.legend()  # Display legend

# Save plots as separate files
#plt.figure(1)  # Assign a figure number
#plt.savefig('covalent_plot.png')  # Save covalent plot

#plt.figure(2)  # Assign a new figure number
#plt.savefig('vdw_plot.png')  # Save vdw plot

#plt.figure(3)  # Assign a new figure number
#plt.savefig('free_particles_plot.png')  # Save free particles plot

# Display the plot
plt.savefig('histogram.png')